# Outputting
permalink: /:categories/:year/:month/:day/:title.html

# Jekyll sitemap plugin config - https://github.com/jekyll/jekyll-sitemap
url: "https://jjmpsp.github.io" # the base hostname & protocol for this site
plugins:
  - jekyll-sitemap

exclude: [.idea/]

# Conversion
markdown:         kramdown
highlighter:      rouge
excerpt_separator: <!--more-->

# Config for your profile.
title:            Joel Murphy
name:             Joel Murphy
role:             Senior Full Stack Developer
avatar:           /theme/img/avatar.jpg

# The theme uses the baseurl throughout, which is useful for running the entire
# site under a subdir, like for this GitHub Pages deployment as a project site.
baseurl: ""

# Add a directory to hold misc pages, just to keep the root directory clean.
include: ["_travel", "_pages", "_portfolio"]

# Collections
collections:
  posts:
    output: true
    title: Posts
    permalink: /blog/:name.html
  projects:
    output: true
    title: Projects
    permalink: /:collection/:name.html
  tutorials:
    output: true
    title: Tutorials
    permalink: /:collection/:name.html
  portfolio:
    output: true
    title: portfolio
    permalink: /:collection/:name.html
  travel:
    output: true
    title: Travel
    permalink: /:collection/:name.html
  product_reviews:
    output: true
    title: Product Reviews
    permalink: /:collection/:name.html
  money_savings:
    output: true
    title: Money Saving
    permalink: /:collection/:name.html


defaults:
# Turn the profile sidebar on for all pages by default, except for the
# collections, where it is off and replaced by useful things on the sidebar.
# To override this one a page, use
#    show_profile: false
# to hide the profile.
  -
    scope:
      path: ""
    values:
      show_profile: true
  -
    scope:
      path: "_posts"
    values:
      show_profile: true
      layout: defaults/post
  -
    scope:
      path: "_portfolio"
    values:
      show_profile: true
      layout: defaults/portfolio
  -
    scope:
      path: "_projects"
    values:
      show_profile: true
      layout: defaults/project
  -
    scope:
      path: "_tutorials"
    values:
      show_profile: true
      layout: defaults/tutorial
  -
      scope:
        path: "_travel"
      values:
        show_profile: true
        layout: defaults/travel
  -
      scope:
        path: "_product-reviews"
      values:
        show_profile: true
        layout: defaults/product-review
  - scope:
      path: "_money_savings"
    values:
      show_profile: true
      layout: defaults/money-saving
  -
    scope:
      path: "list"
    values:
      show_profile: true
      layout: defaults/list

# config for jekyll-html-compress plugin
compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

lastUpdated: 2019-05-09 19:02:05 UTC