# Outputting
permalink: /:categories/:year/:month/:day/:title.html

# Jekyll sitemap plugin config - https://github.com/jekyll/jekyll-sitemap
url: "http://example.com" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap

# Conversion
markdown:         kramdown
highlighter:      rouge
excerpt_separator: <!--more-->

# Config for your profile.
title:            Joel Murphy  # Site title
name:             Joel Murphy             # Your name
role:             Full Stack PHP Developer
avatar:           /theme/img/avatar.jpg   # Path to an avatar image

# The theme uses the baseurl throughout, which is useful for running the entire
# site under a subdir, like for this GitHub Pages deployment as a project site.
baseurl: ""

# Add a directory to hold misc pages, just to keep the root directory clean.
include: ["_travel", "_pages", "_portfolio"]

# Turn the projects into a collection.
collections:
  projects:
    output: true
    title: Projects
    permalink: /:collection/:name.html
  portfolio:
    output: true
    title: portfolio
    permalink: /:collection/:name.html
  travel:
    output: true
    title: Travel
    permalink: /:collection/:name.html


defaults:
# Turn the profile sidebar on for all pages by default, except for the
# collections, where it is off and replaced by useful things on the sidebar.
# To override this one a page, use
#    show_profile: false
# to hide the profile.
  -
    scope:
      path: ""
    values:
      show_profile: true
  -
    scope:
      path: "_posts"
    values:
      show_profile: false
      layout: defaults/post
  -
    scope:
      path: "_portfolio"
    values:
      show_profile: false
      layout: defaults/portfolio
  -
    scope:
      path: "_projects"
    values:
      show_profile: false
      layout: defaults/project
  -
      scope:
        path: "_travel"
      values:
        show_profile: false
        layout: defaults/travel
  -
    scope:
      path: "list"
    values:
      show_profile: false
      layout: defaults/list

lastUpdated: 2018-12-10 19:02:05 UTC