###
### This is a modified version of _config.yml for dev environments only
### This file excludes plugins with long runtimes, reducing build times.
###
# Outputting
permalink: /:categories/:year/:month/:day/:title.html

# Jekyll sitemap plugin config - https://github.com/jekyll/jekyll-sitemap
url: "https://joel-murphy.co.uk"
plugins:
  - jekyll-paginate-v2

exclude: [.idea/,webpack/,webpack.config.js,node_modules/,package.json]

# Pagination:
############################################################

pagination:
  # Site-wide kill switch, if disabled here then it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'blogposts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 4

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
############################################################

# Algolia search
############################################################
algolia:
  application_id: 'FU05W4UZFC'
  index_name: 'prod_index'
  search_only_api_key: 'f25af87c01b2ae2f6578f8d6d0a5497b'
############################################################

# Conversion
markdown:         kramdown
highlighter:      rouge
excerpt_separator: <!--more-->

# Config for your profile.
title:            Joel Murphy
name:             Joel Murphy
role:             Senior Full Stack Developer and R&D expert by day. Cloud, DevOps, Infrastructure, and SysAdmin specialist by night.
avatar:           /theme/img/avatar.jpg

# The theme uses the baseurl throughout, which is useful for running the entire
# site under a subdir, like for athis GitHub Pages deployment as a project site.
baseurl: ""

# Add a directory to hold misc pages, just to keep the root directory clean.
include: ["_pages"]

# Collections
collections_dir: _collections
collections:
  blogposts:
    output: true
    title: Blog Posts
    permalink: /:collection/:name.html
  projects:
    output: true
    title: Projects
    permalink: /:collection/:name.html
  tutorials:
    output: true
    title: Tutorials
    permalink: /:collection/:name.html
  portfolio:
    output: true
    title: portfolio
    permalink: /:collection/:name.html
  travel:
    output: true
    title: Travel
    permalink: /:collection/:name.html
  travel_africa:
    output: true
    title: Travel in Africa
    permalink: /travel/africa/:name.html
  travel_europe:
    output: true
    title: Travel in Europe
    permalink: /travel/europe/:name.html
  product_reviews:
    output: true
    title: Product Reviews
    permalink: /:collection/:name.html
  money_savings:
    output: true
    title: Money Saving
    permalink: /:collection/:name.html


defaults:
  # Turn the profile sidebar on for all pages by default, except for the
  # collections, where it is off and replaced by useful things on the sidebar.
  # To override this one a page, use
  #    show_profile: false
  # to hide the profile.
  - scope:
      path: ""
    values:
      show_profile: true
  - scope:
      path: "_blogposts"
    values:
      show_profile: true
      layout: defaults/blog-post
  - scope:
      path: "_portfolio"
    values:
      show_profile: true
      layout: defaults/portfolio
  - scope:
      path: "_projects"
    values:
      show_profile: true
      layout: defaults/project
  - scope:
      path: "_tutorials"
    values:
      show_profile: true
      layout: defaults/tutorial
  - scope:
      path: "_travel"
    values:
      show_profile: true
      layout: defaults/travel
  - scope:
      path: "_travel_africa"
    values:
      show_profile: true
      layout: defaults/travel
  - scope:
      path: "_travel_europe"
    values:
      show_profile: true
      layout: defaults/travel
  - scope:
      path: "_product-reviews"
    values:
      show_profile: true
      layout: defaults/product-review
  - scope:
      path: "_money_savings"
    values:
      show_profile: true
      layout: defaults/money-saving
  - scope:
      path: "list"
    values:
      show_profile: true
      layout: defaults/list

# sass config
sass:
  style: cCanvas resizeompressed

# config for jekyll-html-compress plugin
compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: [local]